# Site settings
title: MIFind Blog
SEOTitle: MIFind blog | 技术博客
header-img: img/home-bg.jpg
email: mifindxuan@gmail.com
description: "ReactNative, Vue, 前端 , Web/Wap, Android, javascript "
keyword: "ReactNative, Vue, 前端 , Web/Wap, Android, javascript"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     270911334
zhihu_username:     xuan-jia-wei-27
github_username:    MIFind


# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: MIFind
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: b959664f3349ddb0e15b20bd38897dd6
# Google Analytics



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "程序猿吹起牛逼，那可是比较可怕。"
sidebar-avatar: /img/mifind.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "迷路的二十五岁（写一些日常装逼文章）",
        href: "http://mifind.online/yeoman-bootstrap-gulp-page/dist"
    },{
        title: "听说、故事",
        href: "http://mifind.online/VUEONE/one/one/one.html#/"
    },{
        title: "听说、音乐",
        href: "http://mifind.online/VUEONE/one/music/music.html#/"
    },{
        title: "隐藏剧情",
        href: "http://mifind.online/VUEONE/one/about/about.html#/"
    },{
        title: "简历项目",
        href: "http://mifind.online/myResume/"
    }
]
